#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$SHOP_USER" WITH PASSWORD '$SHOP_PASSWORD';
	CREATE DATABASE "$SHOP_DB";
	GRANT ALL PRIVILEGES ON DATABASE "$SHOP_DB" TO "$SHOP_USER";
EOSQL
