name: Server
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Server
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: bank_db
          POSTGRES_PASSWORD: bank_password
          POSTGRES_DB: bank_db
          SHOP_USER: shop_user
          SHOP_PASSWORD: shop_password
          SHOP_DB: shop_db
        volumes:
          - './init-shop-db.sh:/docker-entrypoint-initdb.d/init-shop-db.sh'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java 17 with Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw compile -q
      - name: Run tests with Maven
        run: ./mvnw test -q
