name: Server
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Server
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 17 with Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn compile
      - name: Run tests with Maven
        run: mvn test
