name: Server
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Server
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java 17 with Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw compile -q
      - name: Run tests with Maven
        run: ./mvnw test -q
