name: Terminal
on:
  pull_request:
    branches:
      - main
    # paths:
    #   - 'terminal/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terminal
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.1'
      - name: Analyze project
        run: flutter analyze
      - name: Run tests
        run: flutter test
